#pragma config(Motor,  port8,           flywheelTop,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           flywheelBottom, tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()	{


}

void launchBallMidFlag (int distanceInches)	{
	int angle = 60;
	int flagHeight = 30;
	float initialHeight = 16.821;
	float gravity = 386.4;
	float actualDistance = distanceInches + 6.93;
	float targetRPM;
	//yf = 1/2*a*t^2 + viy*t + yi
	// v = w * r
	// xf/t = vix
	// vix = cos@ * vi
	// viy = sin@ * vi
	// xf/vix = t
	// xf/(cos@ * vi) = t
	//yf = 1/2*a*(xf/(cos@ * vi))^2 + (sin@ * vi)(xf/(cos@ * vi)) + yi
	//30 - 16.821 = 0.5 * 386.4 * (xf/(cos60 * vi))^2 + (sin60 * vi)(xf/(cos60 * vi))
	// 13.179 = 772.8 * (xf/vi)^2 + tan60 * xf
	// (13.179 - (tan60 * xf))/772.8 = xf^2 / vi^2
	// (13.179 - (tan60 * xf))/(772.8 * xf^2) = 1/vi^2
	// (772.8 * xf^2)/(13.179 - (tan60 * xf)) = vi^2
	// sqrt((772.8 * xf^2)/(13.179 - (tan60 * xf))) = vi
	// sqrt((772.8 * xf^2)/(13.179 - (tan60 * xf))) = w * 2 /6.2832
	// sqrt((772.8 * xf^2)/(13.179 - (tan60 * xf))) * 3.1415 = w ; in revolutions per second
	targetRPM = sqrt((772.8 * (actualDistance)^2)/(13.179 - (1.732 * actualDistance))) * 3.1415;

}
